// Objective-C API for talking to github.com/triztian/gomobileprops Go package.
//   gobind -lang=objc github.com/triztian/gomobileprops
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MobileConfig;

@interface MobileConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
@property (nonatomic) NSString* _Nonnull osName;
@property (nonatomic) NSString* _Nonnull osDevice;
@end

FOUNDATION_EXPORT MobileConfig* _Nullable MobileNewConfig(void);

#endif
